server:
  port: 3344

spring:
  application:
    name: cloud-config-service # 注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrhzy/springcloud-config.git #GitHub上面的git仓库名字
          ###搜索目录
          search-paths:
            - springcloud-config
      ####读取的分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版