server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider #服务名称
  cloud:
    nacos:
      discovery:
        #nginx地址
        server-addr: 192.168.45.128:1111 # 配置Nacos地址
        #server-addr: 192.168.45.128:1111 # 配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"